// Public private-network endpoint only; generated by scripts/configure-ai.mjs.
window.ROGGY_AI_CONFIG = Object.freeze({"bridgeUrl":"https://desktop-movehp4.tail990d14.ts.net","smartHomeUrl":"https://desktop-movehp4.tail990d14.ts.net/smart-home","transcriptTimeZone":"America/Chicago"});
