const SUPABASE_URL="https://dplvxsniyqkwlmdzqbyg.supabase.co", SUPABASE_KEY="sb_publishable_4WYS4v4U7PSgXesYNNJUfA_69lJaBX1", KEY="roggy-lists-v1";
const seed={buy:[
["Indoor doormat","Home","Need"],["Outdoor doormat","Home","Need"],["Extended small mirror for office","Office","Want"],["Soft light for office meetings","Office","Want"],["Indoor mood lighting — lamps, LEDs, etc.","Home / Decoration","Eventually"],["Outdoor Christmas lights","Decoration","Eventually"],["Blackout curtains","Home","Need"],["Curtain rods x3","Home","Need"],["Fruit bowl","Kitchen","Want"],["Glass food storage container set","Kitchen","Need"],["Hard reusable ice packs for keeping food cold","Kitchen","Need"],["Soft reusable ice packs for injuries","Health / First Aid","Need"],["Flexible silicone ice trays","Kitchen","Need"]
].map((x,i)=>({id:"b"+(i+1),item:x[0],category:x[1],priority:x[2],quantity:x[0].includes("x3")?"3":"",status:"Looking",notes:"",deleted:false,created:"2026-09-17"})),
groceries:[{id:"g1",item:"Cuties oranges",category:"Produce",priority:"Need",quantity:"1",status:"Looking",notes:"",deleted:false,created:"2026-09-17"}]};
let data={buy:[],groceries:[]},currentList="buy",currentView="active",currentFilter="all";
const $=id=>document.getElementById(id),list=$("list"),dialog=$("itemDialog");
function loadData(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.buy&&x.groceries)return x}catch{} localStorage.setItem(KEY,JSON.stringify(seed));return structuredClone(seed)}
async function request(path,opts={}){const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{...opts,headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json",Prefer:"return=representation",...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function loadCloud(){try{const rows=await request("list_items?select=*&order=created_at.asc");data={buy:[],groceries:[]};for(const r of rows)data[r.list_type].push({id:r.id,item:r.item,category:r.category||"",priority:r.priority||"Need",quantity:r.quantity||"",status:r.status,notes:r.notes||"",deleted:!!r.deleted_at,created:r.created_at});localStorage.setItem(KEY,JSON.stringify(data));render()}catch(e){$("status").textContent="Offline — showing local backup";data=loadData();render()}}
async function saveItem(x){localStorage.setItem(KEY,JSON.stringify(data));await request("list_items?id=eq."+encodeURIComponent(x.id),{method:"PATCH",body:JSON.stringify({item:x.item,category:x.category||null,priority:x.priority||null,quantity:x.quantity||null,status:x.status,notes:x.notes||null,deleted_at:x.deleted?new Date().toISOString():null})})}
async function insertItem(x){const rows=await request("list_items",{method:"POST",body:JSON.stringify({list_type:currentList,item:x.item,category:x.category||null,priority:x.priority||null,quantity:x.quantity||null,status:x.status,notes:x.notes||null})});if(rows?.[0])x.id=rows[0].id;localStorage.setItem(KEY,JSON.stringify(data))}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function render(){const arr=data[currentList],deleted=arr.filter(x=>x.deleted);$("deletedCount").textContent=deleted.length?`(${deleted.length})`:"";$("pageTitle").textContent=currentList==="buy"?"Buy List":"Groceries";$("pageSubtitle").textContent=currentList==="buy"?"Needs first. Luxuries later.":"Food and immediate grocery items.";
document.querySelector(".toolbar").style.display=currentView==="deleted"?"none":"";$("summary").style.display=currentView==="deleted"?"none":"";$("addBtn").style.display=currentView==="deleted"?"none":"";$("priorityFilters").style.display=currentList==="groceries"?"none":"";
const active=arr.filter(x=>!x.deleted),bought=active.filter(x=>x.status==="Bought").length,ready=active.filter(x=>x.status==="Ready to Buy").length;$("summary").innerHTML=`<div><b>${active.length-bought}</b><span>active</span></div><div><b>${ready}</b><span>ready</span></div><div><b>${bought}</b><span>bought</span></div>`;
const q=$("search").value.toLowerCase();let shown=arr.filter(x=>currentView==="deleted"?x.deleted:!x.deleted).filter(x=>currentList==="groceries"||currentFilter==="all"||x.priority===currentFilter).filter(x=>!q||[x.item,x.category,x.notes].join(" ").toLowerCase().includes(q));const rank={Need:0,Want:1,Eventually:2};shown.sort($("sort").value==="name"?(a,b)=>a.item.localeCompare(b.item):(a,b)=>(rank[a.priority]??9)-(rank[b.priority]??9));
list.innerHTML="";if(!shown.length){list.innerHTML='<div class="card empty">Nothing here yet.</div>';return}
shown.forEach(x=>{const c=document.createElement("article");c.className="card "+(x.status==="Bought"?"bought":"");if(currentView==="deleted"){c.innerHTML=`<div class="deleted-row"><div><div class="item-name">${esc(x.item)}</div><div class="meta"><span>${esc(x.category||"Other")}</span></div></div><button class="restorebtn">↩ Restore</button></div>`;c.querySelector(".restorebtn").onclick=()=>{x.deleted=false;x.status="Looking";saveItem(x).catch(showErr);render()};list.appendChild(c);return}
c.innerHTML=`<div class="card-summary"><button class="removebtn icon-action remove-left">✕</button><div class="summary-main"><div class="item-name">${esc(x.item)}${x.quantity&&x.quantity!=="1"?` <small>×${esc(x.quantity)}</small>`:""}</div><div class="meta"><span>${esc(x.category||"Other")}</span><span>${esc(x.status)}</span></div></div><div class="card-controls">${currentList==="buy"?`<button class="prioritybtn icon-action" data-dir="up">↑</button><span class="badge ${esc(x.priority)}">${esc(x.priority)}</span><button class="prioritybtn icon-action" data-dir="down">↓</button>`:""}<span class="chevron">⌄</span></div></div><div class="card-details collapsed"><div class="quick"><button class="statusbtn ${x.status==="Looking"?"selected":""}" data-s="Looking">Looking</button><button class="statusbtn ${x.status==="Ready to Buy"?"selected":""}" data-s="Ready to Buy">Ready</button><button class="statusbtn ${x.status==="Bought"?"selected":""}" data-s="Bought">✓ Bought</button></div>${x.notes?`<div class="detail-notes">${esc(x.notes)}</div>`:""}<div class="bottom-actions"><button class="editbtn">Edit details</button></div></div>`;
c.querySelector(".card-summary").onclick=e=>{if(e.target.closest("button"))return;c.querySelector(".card-details").classList.toggle("collapsed");c.classList.toggle("expanded")};c.querySelector(".removebtn").onclick=()=>{x.deleted=true;saveItem(x).catch(showErr);render()};c.querySelectorAll(".statusbtn").forEach(b=>b.onclick=()=>{x.status=b.dataset.s;saveItem(x).catch(showErr);render()});c.querySelectorAll(".prioritybtn").forEach(b=>b.onclick=()=>changePriority(x,b.dataset.dir));c.querySelector(".editbtn").onclick=()=>openEdit(x);list.appendChild(c)})}
function changePriority(x,dir){const levels=["Eventually","Want","Need"],i=levels.indexOf(x.priority),n=Math.max(0,Math.min(2,i+(dir==="up"?1:-1)));x.priority=levels[n];saveItem(x).catch(showErr);render()}
function openEdit(x){$("dialogTitle").textContent="Edit item";$("itemId").value=x.id;$("item").value=x.item;$("category").value=x.category||"";$("priority").value=x.priority||"Need";$("quantity").value=x.quantity||"";$("itemStatus").value=x.status||"Looking";$("notes").value=x.notes||"";dialog.showModal()}
function openAdd(){$("dialogTitle").textContent=currentList==="buy"?"Add purchase":"Add grocery";$("itemId").value="";$("itemForm").reset();$("priority").value="Need";dialog.showModal()}
$("itemForm").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const id=$("itemId").value;let x=id?data[currentList].find(v=>v.id===id):null;if(!x){x={id:crypto.randomUUID(),deleted:false,created:new Date().toISOString().slice(0,10)};data[currentList].push(x)}Object.assign(x,{item:$("item").value.trim(),category:$("category").value.trim(),priority:$("priority").value,quantity:$("quantity").value.trim(),status:$("itemStatus").value,notes:$("notes").value.trim()});if(id)saveItem(x).catch(showErr);else insertItem(x).catch(showErr);dialog.close();render()});
document.querySelectorAll(".page-tab").forEach(b=>b.onclick=()=>{currentList=b.dataset.list;currentView="active";document.querySelectorAll(".page-tab").forEach(z=>z.classList.toggle("active",z===b));document.querySelectorAll(".sub-tab").forEach(z=>z.classList.toggle("active",z.dataset.view==="active"));render()});document.querySelectorAll(".sub-tab").forEach(b=>b.onclick=()=>{currentView=b.dataset.view;document.querySelectorAll(".sub-tab").forEach(z=>z.classList.toggle("active",z===b));render()});document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll(".filter").forEach(z=>z.classList.toggle("active",z===b));render()});$("search").oninput=render;$("sort").onchange=render;$("addBtn").onclick=openAdd;
$("backupBtn").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="roggy-lists-backup.json";a.click();URL.revokeObjectURL(a.href)};
function showErr(e){$("status").textContent="Sync error: "+e.message} if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");loadCloud();