import { writeFile } from 'node:fs/promises';
const url = new URL(process.env.OLLAMA_BRIDGE_URL || 'invalid');
if (url.protocol !== 'https:' || !url.hostname.endsWith('.ts.net') || url.username || url.password || url.search || url.hash || url.pathname !== '/' || url.port) throw Error('Set OLLAMA_BRIDGE_URL to the private Tailscale Serve HTTPS origin (https://PC.TAILNET.ts.net).');
// Deliberate allowlist: never serialize process.env into the browser bundle.
await writeFile(new URL('../ai-config.js', import.meta.url), `// Public private-network endpoint only; generated by scripts/configure-ai.mjs.\nwindow.ROGGY_AI_CONFIG = Object.freeze(${JSON.stringify({ bridgeUrl: url.origin })});\n`);
console.log('Updated public ai-config.js with the private Tailscale HTTPS address only. Rebuild/redeploy the existing website.');
